# Generated by Django 5.2 on 2025-04-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('fonte', models.CharField(max_length=50)),
                ('potencia_kw', models.FloatField()),
            ],
        ),
    ]
