# Generated by Django 5.2 on 2025-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usina',
            name='fonte',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usina',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
